"""Simple Story Map V2 core contracts.

The package is intentionally independent of the rejected M15 narrative-map stack.
"""

from renpy_story_mapper.story_map_v2.contracts import (
    ArmLineageStep,
    ArmMechanic,
    BranchSummary,
    ChunkExecutionResult,
    ChunkProfile,
    ChunkStatus,
    CoreBranchOutcome,
    CoreChunk,
    CoreEvent,
    DensityMetrics,
    EventAnchor,
    ExecutionMode,
    FailureKind,
    MapperEvent,
    MapperResponse,
    ProviderOrigin,
    ProviderSettings,
    Reachability,
    RunPreview,
    SourceSpan,
    StoryChunk,
    StoryMapCore,
    StoryScope,
)
from renpy_story_mapper.story_map_v2.phase03_contracts import (
    NavigationBinding,
    SourceBinding,
    StoryArmReadModel,
    StoryChoiceReadModel,
    StoryEventReadModel,
    StoryMapProjectEnvelope,
    StoryMapProjectIdentity,
    StoryMapReadModel,
    StorySectionReadModel,
    SynthesisExecutionResult,
    SynthesisPreview,
    SynthesisProviderReply,
    ValidatedSynthesis,
)

__all__ = [
    "ArmLineageStep",
    "ArmMechanic",
    "BranchSummary",
    "ChunkExecutionResult",
    "ChunkProfile",
    "ChunkStatus",
    "CoreBranchOutcome",
    "CoreChunk",
    "CoreEvent",
    "DensityMetrics",
    "EventAnchor",
    "ExecutionMode",
    "FailureKind",
    "MapperEvent",
    "MapperResponse",
    "NavigationBinding",
    "ProviderOrigin",
    "ProviderSettings",
    "Reachability",
    "RunPreview",
    "SourceBinding",
    "SourceSpan",
    "StoryArmReadModel",
    "StoryChoiceReadModel",
    "StoryChunk",
    "StoryEventReadModel",
    "StoryMapCore",
    "StoryMapProjectEnvelope",
    "StoryMapProjectIdentity",
    "StoryMapReadModel",
    "StoryScope",
    "StorySectionReadModel",
    "SynthesisExecutionResult",
    "SynthesisPreview",
    "SynthesisProviderReply",
    "ValidatedSynthesis",
]
